### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by rosalie-baxter** [fac19/week5-EIJO#26]
well done on writing tests!!!! :smiley: :star2:

couple of your server ones are failing - when you're using .includes in this context you also need to include the html around the string  

![failingtest](https://user-images.githubusercontent.com/45801475/78297437-74aeab80-7527-11ea-8cc3-7e31155856c5.png)

i am not sure why... :confused:

**Comment by jamesj-0** [comment]
I think this has been fixed in the latest branch 👍
